/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Cards: typeof import('./src/components/cards.vue')['default']
    MovieDescription: typeof import('./src/components/MovieDescription.vue')['default']
    MovieHeader: typeof import('./src/components/MovieHeader.vue')['default']
    MovieInfo: typeof import('./src/components/MovieInfo.vue')['default']
    MovieTrailer: typeof import('./src/components/MovieTrailer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
